### ISSUE TITLE
Issues list after running to_arch script

### ISSUE THREAD

**Issue by c02y** [sugarykeytone/Manjaro_to_Arch_Linux#19]
1. grub, `Error, symbol "grub_is_lockdown" not found` after every reboot, I spent hours solving this problem, I can select the device from the efi list during the beginning process of the startup using F12, and successfully login into the desktop, but it cannot automatically detect and login into it, I tried grub rescue mode, Live USB recreate grub, efibootmgr, grub-customizer, they can run successfully, but are not fixing the issue.
 - **Solution**: https://bbs.archlinux.org/viewtopic.php?id=256856, https://wiki.archlinux.org/title/GRUB#Default/fallback_boot_path
 - the `# grub-install --target=x86_64-efi --efi-directory=esp --removable` line
2. i3, i3 won't recognize and exec the binary if they are inside your personal PATH such as `~/.local/bin`
 - **Solution**: use its absolute path to exec it, or find a better solution later
3. lightdm, every time you have to type password and Enter twice to login into the desktop,
 - **Solution**:  `sudo lightdm-gtk-greeter-settings` to reconfigure manually
4. hostname got changed to `ubuntu.lan`, weird, don't know why
 - **Solution**: `sudo hostnamectl set-hostname yourhostname` to change it
5. A lot of packages: old, orphan, unnecessary, different name in archlinux repo, no package from the official repo but got moved into AUR
  - **Solution**: do it manually
6. kernel, I install lts kernel in the to_arch script, later I install new kernel, the entry in grub is not updated, the `Arch Linux` entry in the grub is still using the old lts kernel, manjaro will automatically update the grub menu if a new kernel is installed.
 - **Solution**: use `sudo grub-customizer` and set default entry to the `(first entry)`
7. new kernel, when I install new kernel 5.15.2 from linux-lts 5.10.79-1, restart, the new kernel won't boot into the login window, black screen and white blink point
 - **Solution**: don't know
8. kernel management: when I delete the new kernel and restart, it seems the grub entry is not updated, old kernel entries are still in the grub menu
  - **Solution**: run `sudo grub-mkconfig /boot/grub/grub.cfg`
9. Virtualbox: Windows10 guest VM won't start (it has bridge network and shared folder), other VMs are OK
 -**Solution**: reinstall `virtualbox-dkms`, `sudo modprobe vboxdrv` , `sudo modprobe vboxnetflt`, and restart Virtualbox
10. Small issues for several different programs.

Manjaro already takes care of a lot of work automatically, none of the above issues happen in Manjaro, but it also installs a lot of old, orphan, unnecessary packages.

It took over 12 hours for me to sort these out, I'm exhausted.

**Comment by sugarykeytone** [comment]
1. The Grub settings are wrongly configured during your Manjaro install. This is not my fault, as it worked in my hardware.
2. Your i3 settings are very nonstandard. This issue happens because your env variables are completely reset. This script performs a reset to Arch in aspects like env variables, I can't make it seamless.
3. That is related completely your settings.
4. I have a line to change the hostname 'Manjaro' to 'arch'. Maybe it messed up.
5. So? This changes the system to Arch. That is completely expected. ***You should've read the script before you ran it. I explicitly noted to read it first. Oh, you don't know shell scripting?***
6. ***There is a magical thing called the arrow keys, sir.***
7. That's your hardware's fault. Don't blame me.
8. That's in the script. I guess you deleted the "seemingly unnecessary" lines. **All of them are important.**
9. That's because you're using the LTS kernel. Archwiki already says you MUST use the dkms package when using the LTS kernel. Well, RTFM.
10. This isn't seamless. A clean install of Arch would have issues with stock Manjaro programs. Deal with it.
Final comments: You seem to
1. Not read the manual(ArchWiki)
2. Think some random script from Github will be absolutely perfect
These are very bad habits.

**Comment by sugarykeytone** [comment]
This is a duplicate issue for the closed issues. Please look at closed issues carefully before you file an issue.

**Comment by c02y** [comment]
1. this is not a bug report, I'm just listing all the issues or discoveries when I'm using the `to_arch` script
2. I list all the issues and solutions, so if anyone has the problems, he/she can directly use the solutions.
3. several issues are already solved by Manjaro, after deleting manjaro packages/configurations, people seeing this would know they have to handle those things by themselves since the difference between Manjaro and Archlinux is way more than expected.
4. some of them are pure differences between Manjaro and ArchLinux's strategies. 

And
- If I need to read ArchLinux wiki to use this script, why would I use this script? I would do all these commands step by step, not to mention there are step by step articles online already
- This is not an issue page that blaming the script, I'm not saying the script causes all these troubles. So please chill out.

Final comment, thank you for your contribution, it won't be perfect, a lot of work has to be done manually since everyone has a different environment, I'm just hoping it will be better day after day.

**Comment by sugarykeytone** [comment]
ArchWiki does not say anything about converting Manjaro to Arch. It only says about the internals and mechanism of it, and I'm recommending to read it to troubleshoot your errors, not the script itself. Learn English again.
> some of them are pure differences between Manjaro and ArchLinux's strategies.
There are none. They are fundamentally the same. Please don't think something you read in a random blog in the internet is real.
